### PR TITLE
Fix proper timeouts error handling for server.execute

### LINKED ISSUE #407: Bad error handling for time-outs
I have a call to `server.execute` (xolvio/backdoor) that results in timeout. It is located in a Jasmine's `beforeAll` block. 
##### Expected behaviour

When the timeout occurs:
- an error should be thrown immediately, or at the **beginning** of each test, failing the tests.
- the error should contain any information that let me **trace** the bug.
##### Actual behaviour

When the timeout occurs:
- the tests run fully and an error is thrown only by the **end** of each test. [1]
- the thrown error does not contain any information about the call that resulted in the timeout.

[1] it results in unexpected errors being thrown, instead of the timeout one, thus the real cause of the problem ends up being camouflaged.
##### Used version
- Chimp: 0.35.0
- Node.js: 5.11.1
- Operation system: OS X El Capitan
##### Console / Log Output

``` js
Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at tryOnTimeout (timers.js:224:11)
        at Timer.listOnTimeout (timers.js:198:5)
```

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

### PR DESCRIPTION
**Pull request by lucetius**
fixed #407

### CODE REVIEW

File: src/lib/chimp-helper.js [hunk 1]
```diff
@@ -164,6 +164,12 @@ var chimpHelper = {
       global.ddp.execute = function (func) {
         var args = Array.prototype.slice.call(arguments, 1);
         var result;
+        var timeout = process.env['chimp.serverExecuteTimeout'] ? parseInt(process.env['chimp.serverExecuteTimeout']) : 10000;
```
Comment (zvictor) [inline src/lib/chimp-helper.js]: suggestion:
```js
var timeout = parseInt(process.env['chimp.serverExecuteTimeout'] || 10000);
```
