### PR TITLE
Fix embedded screenshots in JSON output

### LINKED ISSUE #575: Embeding screenshots in JSON output causes Chimp to crash.
using the following chimp configs:

```js
screenshotsOnError: true,
saveScreenshotsToReport: true,
jsonOutput: './e2e-results.json',
```

causes following error after the tests finish running:

```
/node_modules/chimp/dist/lib/cucumberjs/cucumber.js:101
          if (_this.options.jsonOutput && JSON.parse(jsonResults).length) {
                                                                 ^

TypeError: Cannot read property 'length' of null
    at ChildProcess.<anonymous> (node_modules/chimp/dist/lib/cucumberjs/cucumber.js:101:66)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

The problem does not happen if the screenshots are saved on disk instead of embed in the json output.

### PR DESCRIPTION
**Pull request by lucetius**
Fixes #575

### CODE REVIEW

**Comment by tiagolr** [comment]
If this works, thanks a lot!

File: src/lib/cucumberjs/cucumber.js [hunk 1]
```diff
@@ -79,8 +79,7 @@ class Cucumber {
       if (!this.cucumberChild.stopping) {
         log.debug('[chimp][cucumber] Cucumber not in a stopping state');
 
-        const result = jsonResults;
-        if (this.options.jsonOutput && JSON.parse(jsonResults).length) {
+        if (this.options.jsonOutput && jsonResults && JSON.parse(jsonResults).length) {
```
Comment (tiagolr) [inline src/lib/cucumberjs/cucumber.js]: After applying this changes manually on my 0.47.2 chimp version, I still get an error similar to #575 :

```
/home/tiagolr/ben/web/node_modules/chimp/dist/lib/cucumberjs/cucumber.js:102
          if (this.options.jsonOutput && jsonResults && JSON.parse(jsonResults).length) {
                          ^

TypeError: Cannot read property 'jsonOutput' of undefined
```

using the flags:
```
    screenshotsOnError: true,
    saveScreenshotsToDisk: true,
    saveScreenshotsToReport: true,
```

Comment (twilczek) [inline src/lib/cucumberjs/cucumber.js]: @tiagolr we verified the fix for it on current Chimp master using the repo you provided in issue description. Can you try again using current Chimp master?
